version: '3.10'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      kafka:
        condition: service_started
    entrypoint: ["/bin/bash", "-c"]
    command: |
      echo "Waiting for Kafka...";
      sleep 10;
      echo "Creating topics: $RAW_TOPIC and $PROCESSED_TOPIC";
      for topic in $RAW_TOPIC $PROCESSED_TOPIC; do
        kafka-topics --create \
          --bootstrap-server kafka:9092 \
          --replication-factor 1 \
          --partitions 3 \
          --topic "$topic" || true;
      done
    networks:
      - kafka-net

  postgres:
    image: postgres:14
    container_name: stl_postgres
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../config/pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  write_service:
    build:
      context: ../
      dockerfile: docker/write_service/Dockerfile
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      DATABASE_URL: "postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DB}"
      KAFKA_BROKER: "kafka:9092"
      RAW_TOPIC: ${RAW_TOPIC}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - kafka-net

  read_service:
    build:
      context: ../
      dockerfile: docker/read_service/Dockerfile
    env_file:
      - ../.env
    ports:
      - "5001:5001"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      DATABASE_URL: "postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DB}"
      KAFKA_BROKER: "kafka:9092"
      RAW_TOPIC: ${RAW_TOPIC}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - kafka-net

  crime_consumer:
    build:
      context: ../
      dockerfile: docker/write_service/Dockerfile
    command: ["python", "-m", "src.write_service.consumers.crime_consumer"]
    env_file:
      - ../.env
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      DATABASE_URL: "postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DB}"
      KAFKA_BROKER: "kafka:9092"
      RAW_TOPIC: ${RAW_TOPIC}
      CRIME_CSV: "/data/crime_data.csv"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - kafka-net
    volumes:
      - ../frontend/crime_data.csv:/data/crime_data.csv:ro

volumes:
  pg_data:

networks:
  kafka-net:
    driver: bridge